version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    ports:
      - '5001:5001'
    restart: always
#   caddy:
#     container_name: caddy
#     image: caddy:2.7.4
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - caddy_data:/data
#       - caddy_config_data:/config
#     depends_on:
#       - server
#     restart: always
#     networks:
#       - caddy_net

# volumes:
#   caddy_data: {}
#   caddy_config_data: {}
#   db_volume: {}

# networks:
#   caddy_net:
#     driver: bridge
